# Generated by Django 4.0.4 on 2022-06-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Коментарий')),
                ('comment_dt', models.DateTimeField(auto_now=True)),
                ('comment_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
