# Generated by Django 4.0.4 on 2022-05-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderCrm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_img', models.ImageField(upload_to='static/img')),
                ('sl_title', models.CharField(max_length=50, verbose_name='Описание')),
                ('sl_text', models.CharField(max_length=200, verbose_name='Текст')),
                ('sl_css', models.CharField(default='-', max_length=20, null=True, verbose_name='Slider_CSS')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
